#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.url= postgresql://mydatabase_68vk_user:vIYfCxj7MSgBbZJM5rmChYVK6nkeHk3B@dpg-d6iqdu0gjchc73dhst4g-a.oregon-postgres.render.com/mydatabase_68vk
#spring.datasource.username=mydatabase_68vk_user
#spring.datasource.password=vIYfCxj7MSgBbZJM5rmChYVK6nkeHk3B
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://dpg-d6iqdu0gjchc73dhst4g-a.oregon-postgres.render.com:5432/mydatabase_68vk
spring.datasource.username=mydatabase_68vk_user
spring.datasource.password=vIYfCxj7MSgBbZJM5rmChYVK6nkeHk3B
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
